name: Node.js CI

on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node-version: ["14.15.3", "15.5.0"]
        double-end: ["", "res.end() ×2"]
        compression: ["", "+compression"]
        include:
          - os: ubuntu-latest
            node-version: 12.20.0
            double-end: res.end() ×2
            compression: +compression
          - os: ubuntu-latest
            node-version: 13.14.0
            double-end: res.end() ×2
            compression: +compression
          - os: ubuntu-latest
            node-version: 14.0.0
            double-end: res.end() ×2
            compression: +compression
    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: install dependencies
        run: npm install

      - name: start server
        run: |
          node ./server.js &
          sleep 10 &&
          curl http://localhost:8080
        env:
          DOUBLE_END: ${{ matrix.double-end != '' }}
          COMPRESSION: ${{ matrix.compression != '' }}

      - name: Redirect to a small page
        run: |
          curl \
            --dump-header - \
            --header "Accept-Encoding: gzip" \
            --location \
            --max-time 10 \
            --output /dev/null \
            http://localhost:8080/redirect\?toSize\=1000

      - name: Redirect to a bigger page
        run: |
          curl \
            --dump-header - \
            --header "Accept-Encoding: gzip" \
            --location \
            --max-time 10 \
            --output /dev/null \
            http://localhost:8080/redirect\?toSize\=100000
